using Content.Client.States;
using Content.Shared.States;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyUI : UIScreen, IStateUserInterface
{
    public ContentState CurrentState { get; set; } = default!;
    public LobbyState LobbyState => (CurrentState as LobbyState)!;
    
    public LobbyUI()
    {
        RobustXamlLoader.Load(this);
    }

    public void OnStateChanged()
    {
        StateButton.Handler = LobbyState.SayHelloFunHandler;
        GoLabel.Text = LobbyState.Message;
    }
}