using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyUI : UIScreen
{
    public LobbyUI()
    {
        RobustXamlLoader.Load(this);
    }
}