using Content.Client.States;
using Content.Shared.States;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyUI : UIScreen, IStateUserInterface
{
    public ContentState CurrentState { get; set; } = default!;
    public LobbyState LobbyState => (CurrentState as LobbyState)!;
    
    public LobbyUI()
    {
        RobustXamlLoader.Load(this);
        GoButton.OnPressed += GoButtonOnOnPressed;
    }

    private void GoButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        LobbyState.SayHello.Invoke();
    }

    public void OnStateChanged()
    {
        GoLabel.Text = LobbyState.Message;
    }
}